name: ci-nestjs-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the desired Node.js version for NestJS

      # Install dependencies
      - run: npm install

      # Run tests
      - run: npm run test -- --coverage  # Assuming you're using Jest for testing

      # Build the NestJS application (compiles TypeScript)
      - run: npm run build

      # Setup QEMU (If Docker is required)
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      # Setup Docker Buildx (If Docker is required)
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3  

      # Build and push Docker image (If Docker is needed for your app)
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: false  # Change to 'true' if you want to push the image to a registry
          tags: eagoncalves/git-actions-nestjs  # Replace with your desired Docker tag
